#!/usr/bin/env python3           //This code is edited from the Magipi Essentials Handbook for the AIY Voice kit
import argparse
import locale
import logging
from aiy.board import Board, Led
from aiy.cloudspeech import CloudSpeechClient
from gpiozero import LED


import RPi.GPIO as GPIO
led = LED(6)

def get_hints(language_code):
    if language_code.startswith('en_'):
        return ('turn on the light',
                'turn off the light',
                'blink the light',
                'goodbye')
    return None

def locale_language():
    language, _ = locale.getdefaultlocale()
    return language



def main():
 logging.basicConfig(level=logging.DEBUG)
 
 parser = argparse.ArgumentParser(description='Assistant service example.')
 parser.add_argument('--language', default=locale_language())
 args = parser.parse_args()
 
 logging.info('Initializing for language %s...', args.language)
 hints = get_hints(args.language)
 client = CloudSpeechClient()

 button = Board.button

 
 GPIO.setmode(GPIO.BCM)
 GPIO.setwarnings(False)
 GPIO.setup(6,GPIO.OUT)

 while True:
     with Board() as board:
         print('Press the button and speak')
         board.button.wait_for_press()
         print('Listening...')
         text = client.recognize(language_code=args.language,
                                    hint_phrases=hints)
     if text is None:
         print('Sorry, I did not hear you.')
     else:
         print('You said "', text, '"')
     if 'turn on the light' in text:
         led.on()
     elif 'turn off the light' in text:
         led.off()
if __name__ == '__main__':
 main()
